baseurl = "https://skaur.us"
defaultContentLanguage = "en"
languageCode = "en"
title = "Dmitry Shalashov"
theme = ["all-links-newtab", "gokarna-tweaks", "gokarna"]
canonifyurls = true
hasCJKLanguage = false
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    avatarURL = "/img/avatar-cropped.jpg"
    author = "Dmitry Shalashov"
    description = """
        Startup co-founder & CTO / Team lead / Backend senior developer
    """
    socialIcons = [
        {name = "linkedin", url = "https://www.linkedin.com/in/skaurus/"},
        {name = "readdotcv", url = "/cv"},
        {name = "github", url = "https://github.com/skaurus"},
        {name = "telegram", url = "https://t.me/beeblebrox"},
        {name = "gmail", url = "mailto:skaurus@gmail.com"},
    ]
    footer = "Dmitry Shalashov"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]
