baseurl = "https://skaur.us/"
title = "Dmitry Shalashov's personal page"
theme = ["md-more-like-notion", "all-links-newtab", "pulp"]
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Dmitry Shalashov"
    avatar = "avatar-cropped.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
        CTO, startup co-founder, Perl/Go developer, Russian emigrant
    """
    publicationYear = "2023"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = 'linkedin'
    title = 'Linkedin'
    # name = 'Blog' #If display text link, cancel comment out
    pre = '<i class="fab fa-brands fa-linkedin-in"></i>' #Choose your favorite font from Font Awesome
    url = 'https://www.linkedin.com/in/skaurus/'
    weight = 10

[[menu.main]]
    identifier = 'cv'
    title = 'CV'
    # name = 'CV'
    pre = '<i class="fa fa-thin fa-code"></i>'
    url = '/cv'
    weight = 20

[[menu.main]]
    identifier = 'github'
    title = 'Github'
    # name = 'GitHub'
    pre = '<i class="fab fa-github fa-lg"></i>'
    url = 'https://github.com/skaurus'
    weight = 30

[[menu.main]]
    identifier = 'telegram'
    title = 'Telegram'
    # name = 'Telegram'
    pre = '<i class="fab fa-brands fa-telegram"></i>'
    url = 'https://t.me/beeblebrox'
    weight = 40

[[menu.main]]
    identifier = 'email'
    title = 'Email'
    # name = 'Email'
    pre = '<i class="fa fa-envelope fa-lg"></i>'
    url = 'mailto:skaurus@gmail.com'
    weight = 50
